name: "Deploy to BalenaCloud"
branding:
  color: "yellow"
  icon: "box"
description: "Deploy your code to BalenaCloud using balena-cli (local build and push)"
inputs:
  api-token:
    description: "BalenaCloud API Key"
    required: true
  application-name:
    description: "The name of the BalenaCloud Application that you'll be pushing to"
    required: true
  application-path:
    description: "Optional. Provide a subfolder path to your BalenaCloud application, example: ./balena-wpe"
    default: "."
  version:
    description: "The version of the release being deployed"
    default: "0.0.0"
  draft:
    description: "Mark as draft release"
    required: false
    default: 'false'
  cache_from:
    description: "Comma-separated list (no spaces) of image names for build cache resolution"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    API_TOKEN: ${{ inputs.api-token }}
    APPLICATION_NAME: ${{ inputs.application-name }}
    APPLICATION_PATH: ${{ inputs.application-path }}
    VERSION: ${{ inputs.version }}
    DRAFT: ${{ inputs.draft }}
    CACHE_FROM: ${{ inputs.cache_from }}
